### ISSUE TITLE
Camera Not Working on Android 2.3 Phones

### ISSUE THREAD

**Issue by acormack** [rhomobile/rhodes#37]
After building api-samples with Rhodes 3.0.2 / Android SDK 2.3.3 and installing on both HTC Wildfie S (running Android 2.3.3) and Nexus S (running 2.3.4) The application runs perfectly except for accessing the camera.

They both give the same error message:

undefined method 'get_camera_info' for Camera:Module

I have edited the build.yml and added the camera capability.  

I have also tried building with rhodes 3.0.2.beta.1 and get the same error
